-- Run this in your Supabase SQL Editor to add test grant data
-- These grants are designed to test the NLP matching functionality

INSERT INTO public.grants (title, description, issue_area, scope, kpis, funding_min, funding_max, application_due_date, eligibility_criteria, funder_name, funder_url, source_url, is_active) VALUES

-- Environment grants
('Green Communities Initiative', 
 'Supporting community-led environmental projects including urban gardens, tree planting, and sustainability education programs. We prioritize projects that demonstrate measurable environmental impact and community engagement.',
 'Environment', 
 'National', 
 ARRAY['Carbon reduction', 'Trees planted', 'Community members engaged'],
 10000, 50000, 
 '2026-03-31',
 'Registered non-profit organizations with environmental focus',
 'GreenFuture Foundation',
 'https://greenfuture.org',
 'https://greenfuture.org/grants',
 true),

('Climate Action Small Grants',
 'Quick-disbursement grants for urgent climate adaptation projects. Ideal for organizations needing rapid funding for environmental emergencies or time-sensitive opportunities.',
 'Environment',
 'Local',
 ARRAY['Response time', 'Beneficiaries reached', 'Emissions avoided'],
 5000, 15000,
 '2026-02-28',
 'Community organizations addressing climate change',
 'Climate Emergency Fund',
 'https://climatefund.sg',
 'https://climatefund.sg/apply',
 true),

-- Education grants  
('Youth Education Excellence Fund',
 'Empowering educational programs that serve underprivileged youth. Focus areas include STEM education, digital literacy, and after-school enrichment programs.',
 'Education',
 'National',
 ARRAY['Students served', 'Test score improvement', 'Program completion rate'],
 25000, 100000,
 '2026-04-15',
 '501(c)(3) or equivalent non-profit status required',
 'Education Forward Foundation',
 'https://educationforward.org',
 'https://educationforward.org/youth-fund',
 true),

('Digital Literacy for All',
 'Bridging the digital divide through technology access and training. Supports programs providing computer equipment, internet access, and digital skills training to underserved communities.',
 'Education',
 'Local',
 ARRAY['Devices distributed', 'Training hours delivered', 'Digital skills certifications'],
 15000, 40000,
 '2026-05-01',
 'Non-profits serving communities with limited technology access',
 'Tech Access Singapore',
 'https://techaccess.sg',
 'https://techaccess.sg/grants',
 true),

-- Healthcare grants
('Community Mental Health Initiative',
 'Supporting mental health awareness and access programs. Funding available for counseling services, mental health education, and community support networks.',
 'Healthcare',
 'National',
 ARRAY['Counseling sessions provided', 'Awareness reach', 'Support group participants'],
 30000, 80000,
 '2026-03-15',
 'Healthcare-focused non-profits with licensed practitioners',
 'Mental Wellness Foundation',
 'https://mentalwellness.org',
 'https://mentalwellness.org/community-grants',
 true),

('Health Access for Seniors',
 'Improving healthcare access for elderly populations through mobile health clinics, home visits, and preventive care programs.',
 'Healthcare',
 'Local',
 ARRAY['Seniors served', 'Health screenings completed', 'Referrals to care'],
 20000, 60000,
 '2026-04-30',
 'Organizations serving elderly populations',
 'Senior Care Alliance',
 'https://seniorcare.sg',
 'https://seniorcare.sg/grants',
 true),

-- Arts & Culture grants
('Community Arts Engagement Fund',
 'Bringing arts and culture to underserved communities through theater performances, art workshops, music programs, and cultural festivals.',
 'Arts & Culture',
 'Local',
 ARRAY['Events held', 'Participants engaged', 'Artists supported'],
 8000, 35000,
 '2026-05-15',
 'Arts organizations with community outreach programs',
 'Arts Council Singapore',
 'https://artscouncil.sg',
 'https://artscouncil.sg/community-fund',
 true),

('Heritage Preservation Grant',
 'Supporting projects that document, preserve, and celebrate cultural heritage. Includes oral history projects, traditional crafts preservation, and heritage education.',
 'Arts & Culture',
 'National',
 ARRAY['Heritage items preserved', 'Stories documented', 'Youth engaged in heritage'],
 15000, 50000,
 '2026-06-01',
 'Non-profits focused on cultural preservation',
 'Heritage Foundation',
 'https://heritagefund.sg',
 'https://heritagefund.sg/grants',
 true),

-- Community Development grants
('Neighborhood Strengthening Initiative',
 'Building stronger communities through neighborhood improvement projects, community spaces, and resident engagement programs.',
 'Community Development',
 'Local',
 ARRAY['Residents engaged', 'Community events held', 'Volunteer hours contributed'],
 12000, 45000,
 '2026-04-01',
 'Neighborhood associations and community organizations',
 'Community First Foundation',
 'https://communityfirst.sg',
 'https://communityfirst.sg/apply',
 true),

('Social Enterprise Starter Grant',
 'Seed funding for social enterprises addressing community needs. Supports innovative approaches to social problems through sustainable business models.',
 'Community Development',
 'National',
 ARRAY['Jobs created', 'Social impact metrics', 'Revenue sustainability'],
 20000, 75000,
 '2026-03-20',
 'Early-stage social enterprises (under 3 years)',
 'Social Innovation Fund',
 'https://socialinnovation.sg',
 'https://socialinnovation.sg/starter',
 true),

-- Youth Development grants
('Youth Leadership Development',
 'Developing the next generation of community leaders through mentorship, leadership training, and youth-led project funding.',
 'Youth Development',
 'National',
 ARRAY['Youth trained', 'Projects completed', 'Leadership roles assumed'],
 10000, 40000,
 '2026-05-30',
 'Youth-serving organizations with leadership programs',
 'Future Leaders Foundation',
 'https://futureleaders.sg',
 'https://futureleaders.sg/grants',
 true),

('At-Risk Youth Support Fund',
 'Providing intervention and support services for at-risk youth including counseling, job training, and mentorship programs.',
 'Youth Development',
 'Local',
 ARRAY['Youth supported', 'School retention rate', 'Employment placements'],
 25000, 70000,
 '2026-04-20',
 'Organizations with proven track record serving at-risk youth',
 'Youth Opportunity Network',
 'https://youthopportunity.sg',
 'https://youthopportunity.sg/apply',
 true);
